### ISSUE TITLE
Character limit

### ISSUE THREAD

**Issue by YesdXploiter** [joserodpt/RealScoreboard#14]
How to write more characters than this? Why do I have a limit on my server?
Name is SomeName, not SomeN. It doesn't say ping the player. Why?
Server version: 1.16.4
Client version: 1.12.2
Plugins:
AncientGates
EssentialsX
HideStream
HolographicDisplays
ImageMaps
LuckPerms
RealScoreboard
TAB
ViaBackwards
ViaRewind
ViaVersion
WorldEdit
WorldGuard

Please help
![image](https://user-images.githubusercontent.com/43494452/111745020-206a1c00-889d-11eb-9edc-5a361ae17cb7.png)

**Comment by joserodpt** [comment]
Are you using ViaVersion?

**Comment by YesdXploiter** [comment]
Yes

**Comment by joserodpt** [comment]
ViaVersion doesnt support long lines in 1.12.2
Also my plugin works best between 1.13 and 1.16

**Comment by YesdXploiter** [comment]
Sad :(
