### ISSUE TITLE
Error from console

### ISSUE THREAD

**Issue by VenixMC** [joserodpt/RealScoreboard#15]
https://paste.gg/p/anonymous/4f32226b2e5945dfbc168600144553ac/revisions
![Screenshot from 2021-03-24 18-42-48](https://user-images.githubusercontent.com/31991935/112305062-d637cf00-8cd0-11eb-8686-9ea0d2320561.png)

**Comment by joserodpt** [comment]
Can you show me your config?

**Comment by VenixMC** [comment]
https://paste.gg/p/anonymous/4dc77b7ca66348b0836c14521da6f46c

**Comment by joserodpt** [comment]
closed on discord.
