### ISSUE TITLE
PlayerJoinEvent error

### ISSUE THREAD

**Issue by baailey** [joserodpt/RealScoreboard#18]
17.04 02:01:33 [Server] ERROR Could not pass event PlayerJoinEvent to RealScoreboard v11-4-2021 Build 1
17.04 02:01:33 [Server] INFO java.lang.NullPointerException: null
17.04 02:01:33 [Server] INFO at josegamerpt.realscoreboard.managers.PlayerManager.check(PlayerManager.java:31) ~[?:?]
17.04 02:01:33 [Server] INFO at josegamerpt.realscoreboard.managers.PlayerManager.join(PlayerManager.java:46) ~[?:?]
17.04 02:01:33 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor241.execute(Unknown Source) ~[?:?]
17.04 02:01:33 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:167) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:540) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:150) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1439) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
17.04 02:01:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by joserodpt** [comment]
Hi there, thanks for the report.
Please tell me if this happens at all times?
Thanks

**Comment by baailey** [comment]
Everytime a player joins this error appears

**Comment by joserodpt** [comment]
Does that happen with default config & data?

**Comment by baailey** [comment]
I'm not sure, but since this is on the main server I don't really wish to resort back to default config as players have no reason to see that. However, here is my config if anything stands out - https://gist.github.com/baailey/c33dd9aba6aadb4748f7088dd24c071f

**Comment by joserodpt** [comment]
Please try this build. Thanks!

[RealScoreboard.zip](https://github.com/JoseGamerPT/RealScoreboard/files/6329583/RealScoreboard.zip)

**Comment by baailey** [comment]
The new jar has fixed this issue.
