### ISSUE TITLE
Real Scoreboard Suddenly Not Working.

### ISSUE THREAD

**Issue by charlie-works** [joserodpt/RealScoreboard#25]
Config: https://mcpaste.io/07074fc6f63c33fa

Java version is 16 and it just suddenly stopped working.

**Comment by joserodpt** [comment]
Config seems ok. Send Logs.

**Comment by charlie-works** [comment]
https://mcpaste.io/5a786c5781fde914

**Comment by charlie-works** [comment]
Scoreboard works for everyone but special apparently, just found that out.

**Comment by charlie-works** [comment]
Scoreboard is showing up, but it's just a small transparent rectangle on lunar client

**Comment by joserodpt** [comment]
Are you using any kind of ViaVersion plugin?
You can also join my Discord, so we can chat about it.

**Comment by charlie-works** [comment]
I managed to fix it, I think I added an extra space to the config :D
