### ISSUE TITLE
Scoreboard disappears after showing MCMMO stats scoreboard

### ISSUE THREAD

**Issue by somekoder** [joserodpt/RealScoreboard#30]
Hi! Not sure if it's a bug, or if there's already a work around. I noticed that if we show any scoreboards provided by MCMMO with /mcstats, it will remove any scoreboards created in RealScoreboard until rejoining the server.

**Comment by joserodpt** [comment]
Hi there. The reason for that is that RealScoreboard uses a packet-based system for displaying the scoreboard
