### ISSUE TITLE
Ping not working 1.18

### ISSUE THREAD

**Issue by UsefullSpoon** [joserodpt/RealScoreboard#32]
the %ping% placeholder comes back as either 1 or 0

**Comment by Test-Account666** [comment]
For me Realscoreboard doesn't work at all in 1.18

**Comment by joserodpt** [comment]
Sorry for the late responses.
@UsefullSpoon can you provide further details?

**Comment by joserodpt** [comment]
> For me Realscoreboard doesn't work at all in 1.18

Can you further elaborate on why?

**Comment by joserodpt** [comment]
Also join the Discord server

**Comment by Test-Account666** [comment]
> > For me Realscoreboard doesn't work at all in 1.18
> 
> Can you further elaborate on why?

I just forgot to update the config file, sorry

**Comment by UsefullSpoon** [comment]
> Sorry for the late responses. @UsefullSpoon can you provide further details?

yes well i changed the config the scoreboard ping to %ping% and it only shows 1ms consistently

**Comment by Test-Account666** [comment]
> > Sorry for the late responses. @UsefullSpoon can you provide further details?
> 
> yes well i changed the config the scoreboard ping to %ping% and it only shows 1ms consistently

I made a pull request fixing this issue and JoseGamerPT accepted it.

So you just need to update to the latest version of RealScoreboard
