### ISSUE TITLE
API

### ISSUE THREAD

**Issue by nothendev** [joserodpt/RealScoreboard#35]
Make an API, please

**Comment by joserodpt** [comment]
What kind of features are you expecting from the api?

**Comment by nothendev** [comment]
get boards, set boards, create custom non-file temp boards and display them

**Comment by neziw** [comment]
@JoseGamerPT What do you think to split the maven project into two modules (like most plugins or projects like BungeeCord) called API and Plugin /Core? In my opinion, if you want to make an API to RealScoreboard, developers should only have access to classes and methods that they need (e.g managers and other), not all of them (like main plugin class).

**Comment by joserodpt** [comment]
Seems very good, it will be Very Nice to have the codebase splitted with modules

**Comment by neziw** [comment]
Feature Being implemented, thanks.

**Comment by joserodpt** [comment]
Feature added. Thanks for the suggestion!
