### ISSUE TITLE
Adicionar o suporte ao mcMMO

### ISSUE THREAD

**Issue by FITFC** [joserodpt/RealScoreboard#37]
Adicionar suporta para poder utilizar o mcTOP sem inutilizar o RSB.
Se tiver interesse posso até mandar alguns plugins de exemplo...
Porém o RSB tem uma função específica que eu utilizo então... seria bom vê o RSB suportando o maior plugin de skill's da comunidade SpigotMC

**Comment by joserodpt** [comment]
TODO

McMMO throws a McMMOScoreboardRevertEvent that you can listen to, where you can then re-enable the active scoreboard on the player

https://github.com/mcMMO-Dev/mcMMO/tree/master/src/main/java/com/gmail/nossr50/events/scoreboard

**Comment by joserodpt** [comment]
Feature Being implemented, thanks for the suggestion!
