### ISSUE TITLE
Fix Time

### ISSUE THREAD

**Issue by FQQD** [joserodpt/RealScoreboard#40]
Excuse me, is there any way to display the ingame time on the scoreboard or a t least edit the timezone, because where i live, the time goes 2 hours later than displayed on the scoreboard timer.
Thank you,
FQQD

**Comment by joserodpt** [comment]
You can put an offer that adjusts to the hours in config.yml:
    Offset: 0

**Comment by FQQD** [comment]
thank you, but what about the ingame time?

**Comment by joserodpt** [comment]
regarding in-game time, you can use some of the placeholderapi extensions
