### ISSUE TITLE
Not compatible with luckperms

### ISSUE THREAD

**Issue by liltim1** [joserodpt/RealScoreboard#5]
This is the pastebin of the error spamm in console:
https://pastebin.com/r4gGJ0Xv
This is what luckperm devs said:
https://prnt.sc/10aqxxo

**Comment by joserodpt** [comment]
Hi there!
Please test this .jar file and see if it solves your problem.
Check also if there is something else broken please.
[RealScoreboard.zip](https://github.com/JoseGamerPT/RealScoreboard/files/6064652/RealScoreboard.zip)

**Comment by liltim1** [comment]
> Hi there!
> Please test this .jar file and see if it solves your problem.
> Check also if there is something else broken please.
> [RealScoreboard.zip](https://github.com/JoseGamerPT/RealScoreboard/files/6064652/RealScoreboard.zip)

I'll try it out when I get home
Also if you use the plugin CombatLogx and you get into combat the scoreboard from combatlogx takes over and after you're out of combat the "Realscoreboard" is gone, and u can't get it back unless you do /sb reload now that u have removed /sb toggle

**Comment by joserodpt** [comment]
i didnt remove /sb toggle. its still there
Check with this new version if it works

**Comment by liltim1** [comment]
Alright /sb toggle works on this version u sent me now, it didn't work on the spigot one I downloaded after u updated it
Imma let you know if it starts spamming errors in the console when my players get online

**Comment by joserodpt** [comment]
But it's working? 
Do you notice any performance improvement?

**Comment by liltim1** [comment]
It's working yes
And there was definetly a huge performance boost, it used to leak memory and drop TPS by a lot but that was fixed with the Sunday update

**Comment by joserodpt** [comment]
Do you have Discord so we can chat further? Thanks

**Comment by liltim1** [comment]
I was about to ask you that as well you can add me Tim#5330
Or u can join my server: https://discord.com/invite/PptFg74qxy

**Comment by joserodpt** [comment]
issue seems to be fixed in the latest commit.
