### ISSUE TITLE
Alternatywne rozwijanie statystyk/informacji na SB

### ISSUE THREAD

**Issue by Tobiczek** [joserodpt/RealScoreboard#50]
![image](https://user-images.githubusercontent.com/114435370/202722071-9c0fce0c-0dc0-420e-92be-dc09d3fdc191.png)

Bazowałoby to na tym że w jakiś sposób można byloby zrobić by wyświetlaly się informacje dla osób które posiadają jakies dodatkowe permisje lub nie ||Ewentualnie jakies inne lepsze rozwiązanie.

W chwili nie posiadania na przykład wyspy/klanu czy cokolwiek widnialaby chociazby informacja w jaki sposób zrobić/założyć go. Nastepnie po dołączeniu do wyspy/klanu itd lub załozeniu dodatkowe informacje względem nich pojawiłyby się na scoreboard

**Comment by Tobiczek** [comment]
It would be based on the fact that somehow it could be made to display information for people who have some additional permissions or not || Or some other better solution.

When you don't have, for example, an island/clan or whatever, there would be at least information on how to make/put it on. Then after joining an island/clan etc. or setting up additional information about them would appear on the scoreboard

**Comment by neziw** [comment]
Maybe in future. It's a lot of hard work to make it.
