### ISSUE TITLE
: is not supported

### ISSUE THREAD

**Issue by titivermeesch** [joserodpt/RealScoreboard#56]
I have a placeholder that returns `12:23:11` for example (a time value) but it shows up as `%img_43%` in the end (sometimes some other number as well).

This does not happen if I configure the placeholder to not include `:`.

This is closely related to #52 but even after installing the latest version from Spigot as of today it does not fix the issue

**Comment by neziw** [comment]
@titivermeesch Can you try with this build - https://github.com/JoseGamerPT/RealScoreboard/actions/runs/3721403658 ?

**Comment by titivermeesch** [comment]
Seems to fix it yes.

Didn't test it myself but I have one the players that uses my plugin (the one providing the placeholder) who confirms that fixes it

**Comment by neziw** [comment]
I tested myself and works fine. Thanks !
