### ISSUE TITLE
McMMO Suport Issue

### ISSUE THREAD

**Issue by GlowheadS** [joserodpt/RealScoreboard#59]
Seems to be a problem turning McMMO support to "true" instead of default "false"

Upon players joining it completely removes the scoreboard after 5 seconds and players are forced to activate with /sb toggle to "ON" when for some reason it's "OFF" to begin with, even though RealScoreboard-Disabled-By-Default: false

**Comment by neziw** [comment]
Will look into when I have time, thanks

**Comment by GlowheadS** [comment]
Hi, just checking in. Is there any temporary work around?

**Comment by neziw** [comment]
Probably no

**Comment by joserodpt** [comment]
Hi there. The problem still persists? The code seems fine.

**Comment by neziw** [comment]
Closing due to inactiviy. Reopen or create new issue if you have still having the same problem.
