### ISSUE TITLE
Rainbow color not working 

### ISSUE THREAD

**Issue by VenixMC** [joserodpt/RealScoreboard#6]
![image](https://user-images.githubusercontent.com/31991935/109967184-b0e42080-7d23-11eb-9784-f47a8184847b.png)

MC 1.16.5

**Comment by joserodpt** [comment]
Fixed in this commit.
https://github.com/JoseGamerPT/RealScoreboard/commit/fafe58d41a459fce6c40eda4a52dd9b8051a2a17
