### ISSUE TITLE
My friends can't see the rsb settings I created

### ISSUE THREAD

**Issue by Frapop** [joserodpt/RealScoreboard#62]
my problem is that in the settings in aternos I created my own rsb setting but my friends can't see them how to fix it?   I am attaching photos of my rsb and a view from my friend

![16828948991911976058259071948162](https://user-images.githubusercontent.com/132233915/235379502-32464251-d752-4ddc-a251-3e4953239edb.jpg)
![16828949169933880641883844530668](https://user-images.githubusercontent.com/132233915/235379516-3197885b-75de-4212-af8a-e60b1ea36f4b.jpg)

**Comment by joserodpt** [comment]
Have you assigned the correct permissions?

**Comment by joserodpt** [comment]
Closed, no further reply from reporter.
