### ISSUE TITLE
Plugin does not exist after installing plugin

### ISSUE THREAD

**Issue by TheyCallMeFatbird** [joserodpt/RealScoreboard#64]
So I was adding the RealScoreBoard mod on my friends Spigot server for 1.20.1 but when I went in, there was no scoreboard or commands.
What do I do?

**Comment by joserodpt** [comment]
Hi there. Please send your log file, and Also try the plugin on a server with no other plugins for testing.

**Comment by TheyCallMeFatbird** [comment]
I cant send the log because its my friends server but Ill try the plugin on another server

**Comment by joserodpt** [comment]
Ok then, but if the problem persists the log file Will be required.

**Comment by joserodpt** [comment]
Issue closed, no further reply from reporter
