### ISSUE TITLE
The scoreboard doesnt show up

### ISSUE THREAD

**Issue by MrFalconDK** [joserodpt/RealScoreboard#65]
After updating to version 1.20.2 MC, the scoreboard doesnt show up in the latest plugin release.

There are no errors og warns in console. Commands work just fine (/sb reload, /sb toggle) but doesnt do anything.

Even tried to use the default config but it still doesnt work.

Plz fix the issue

**Comment by joserodpt** [comment]
Hi there. 1.20.2 support is broken, I'm waiting for the fastboard dev to deploy the support for the library repository

**Comment by joserodpt** [comment]
Should be fixed in the recent updates.
