### ISSUE TITLE
1.3.2 plugin version Virus detected

### ISSUE THREAD

**Issue by CutieAshlynn** [joserodpt/RealScoreboard#66]
I went to update this plugin on my server and when downloading the new version is detected a virus in the file i wanted to see whats going on as this never has happened to me before on this plugin until now also just to say i will not be disabling my virus protection at all i just want to know what was added to the plugin to cause a virus in it?

**Comment by joserodpt** [comment]
Hi there!
You're like the third person that says that, and I really don't know why.
I just updated the Library that I use under the hood for the scoreboard, the commit is here you can check it: https://github.com/joserodpt/RealScoreboard/commit/762fff27c4a292997583084320d35a2f37536391

**Comment by CutieAshlynn** [comment]
![vi](https://github.com/joserodpt/RealScoreboard/assets/83934629/989f9d0e-69e1-48fb-ba3e-cb965c566f32)


Thats what i get every time i download it.

**Comment by joserodpt** [comment]
I would reccomend to update your antivirus engine Wacatac.H!ml is known for being flagged as a false positive by Microsoft, the current version of Windows Defender will allow the download with no problems.
