### ISSUE TITLE
'/rsb toggle' does not toggle the scoreboard entirely

### ISSUE THREAD

**Issue by Folas1337** [joserodpt/RealScoreboard#67]
With the default setup using '/rsb toggle', the scoreboard is only reduced to the first line with its animations turned off and using '/rsb toggle' again makes it reappear.

This is the scoreboard when turning it off:
![image](https://github.com/joserodpt/RealScoreboard/assets/39222968/ba1aba2a-d846-44bb-94b0-a2852048c244)

This is when having it on:
![image](https://github.com/joserodpt/RealScoreboard/assets/39222968/6561957f-67b5-4cc2-9717-f65f0550d3e8)

I'm really not sure why this is happening at all and I've changed nothing about the default settings of the plugin.

**Comment by joserodpt** [comment]
Thanks for reporting, I will look into it next week, or when I have some spare time

**Comment by Folas1337** [comment]
This is still happening, when is this being looked into? :)

**Comment by joserodpt** [comment]
Hi there! Kindly test this dev version of the plugin, and please give me some feedback after, thanks!
[RealScoreboard.jar.zip](https://github.com/joserodpt/RealScoreboard/files/14865015/RealScoreboard.jar.zip)

**Comment by Folas1337** [comment]
> Hi there! Kindly test this dev version of the plugin, and please give me some feedback after, thanks! [RealScoreboard.jar.zip](https://github.com/joserodpt/RealScoreboard/files/14865015/RealScoreboard.jar.zip)

With that version I'm getting literally no scoreboard at all, no matter if I toggle it on or off :(

**Comment by joserodpt** [comment]
Are there any errors in the console? Is the plugin activated?

**Comment by Folas1337** [comment]
> Are there any errors in the console? Is the plugin activated?

Oh my bad, must've been something on my test server. Tried again on a clean one and there it seems to be working fine :)

I shall close this ticket and you can release the bug fix whenever you want to :)
