### ISSUE TITLE
Is there any way to connect my internal expansion of placeholder api? 

### ISSUE THREAD

**Issue by websorokinweb** [joserodpt/RealScoreboard#71]
I created my own internal expansion of papi. I understand that it is not registered/connected within your real scoreboard plugin. But is there any way to do so?

**Comment by joserodpt** [comment]
What do you mean by internal expansion?

**Comment by websorokinweb** [comment]
https://wiki.placeholderapi.com/developers/creating-a-placeholderexpansion/#making-an-internal-expansion

They also have external expansion, but my placeholders would depend on my plugin state, so I chose internal

**Comment by websorokinweb** [comment]
@Override
            public @NotNull String getIdentifier() {
                return "ocm";
            }
            
Sorry for bothering, it was issue with using placeholders. I tried to use them without my internal prefix like %demo% while I needed to use it with %ocm_demo%
