### ISSUE TITLE
[Feature request] New placeholder for current tps

### ISSUE THREAD

**Issue by k-jiang** [joserodpt/RealScoreboard#74]
Can we have a `%tps%` placeholder for the current tps please?

**Comment by joserodpt** [comment]
You can use a placeholder from PlaceholderAPI: https://wiki.placeholderapi.com/users/placeholder-list/
<img width="433" alt="image" src="https://github.com/joserodpt/RealScoreboard/assets/18755024/14c0e302-d740-4862-857d-f9191d36e3e7">
