### ISSUE TITLE
[BUG] Config option for disabled worlds not working

### ISSUE THREAD

**Issue by OreoKirby** [joserodpt/RealScoreboard#76]
### Minecraft's Version

Paper version 1.21-97

### Plugin's Version

RealScoreboard 1.4.3 dev 18

### Describe the bug

The scoreboard is not enabling/disabling properly when attempting to use `Disabled-Worlds` config list option with `World-Scoreboard-Switch` set to "true" and a world is listed as disabled. The expected behavior would be for the Scoreboard to show in all worlds EXCEPT the one(s) specified in the disabled-list. Currently, the scoreboard is disabled in ALL worlds except the default "world" when setting the above options.

Opposite - If `World-Scoreboard-Switch` is set to "false" the scoreboard will correctly be enabled in ALL worlds.

### To Reproduce

1. Set config.yml line to switch scoreboards on world change to true.
```
World-Scoreboard-Switch: true
```
2. Add a list item to  the disabled worlds list.
```
  Disabled-Worlds:
  - world_nether
```
3. Restart server or Reload the plugin.
4. Confirm the scoreboard is viewable in the Overworld "world".
5. Teleport to the Nether "world_nether" using commands or a physical portal.
6. See that the scoreboard is NOT enabled.
7. Teleport to the End "world_the_end" using commands or a physical portal.
8. See that the scoreboard is ALSO NOT enabled.
### Additional Information

I am also using the plugin Multiverse 1.21-73-3b45454. It is worth noting that this problem occurs in both worlds added by this plugin and the default "world_nether" and "world_the_end".

**Comment by joserodpt** [comment]
Hi! Thanks for the report. I will look into this when I have time.
If you're knowledgeable about code, feel free to take a look at the repo and maybe pinpoint a possible solution!

**Comment by joserodpt** [comment]
Please test this jar file:
[RealScoreboard.jar.zip](https://github.com/user-attachments/files/16283186/RealScoreboard.jar.zip)

**Comment by OreoKirby** [comment]
Thanks for looking into this! I tried out the jar and can confirm the new code is running as the config was upgraded to Version: 18.

However, it looks to be that the issue is still happening with the same behavior. I also tried forcing a `/rsb reload` while in the worlds that should NOT be disabled and the scoreboard stayed disabled. When testing the opposite again with `World-Scoreboard-Switch: false` it does still correctly show the scoreboard in all worlds.

**Comment by joserodpt** [comment]
I repeated your "To Reproduce" steps and found it was working. Do the same steps continue not to work?

**Comment by OreoKirby** [comment]
Apologies, I realized my steps were not quite accurate as it requires 3 worlds to test - I have edited the reproducing steps above! In my old example; disabling just the Nether and not seeing it there is expected behavior. The unexpected behavior is that even though The End is NOT in the disabled list the scoreboard is disabled there as well. 

In my exact case I have multiple additional worlds provided through Multiverse, one of which is a "Minigames" world that has multiple arenas that handle their own scoreboards and do not play well with the base RealScoreboard board enabled all the time. In past server versions my config files for RealScoreboard were the same as they are now and "world_void" was the ONLY world on the `Disabled-Worlds` list. Any other world the player was in the scoreboard would show just fine, but if they visited "world_void" it would not show, as expected. 

Currently, for some reason, if `World-Scoreboard-Switch` is true the scoreboard will ONLY show in "world". I tried testing removing Multiverse as well using only the 3 default worlds and it had the same result. However, if `World-Scoreboard-Switch` is false the scoreboard has no problem showing in ALL worlds which is why I thought it had something to do with the world switch bool.

**Comment by OreoKirby** [comment]
Solved! (or at least now working this way)

I am unsure why my config used to work before for previous versions, but by adding all of the worlds I want the scoreboard to show under the `Other-Worlds` list in "scoreboards.yml" it is now showing. It is essentially a white-list this way instead of the reverse using the blocked-list, but is effectively achieving the way I was going for.

As far as source code goes - it is still probable that the configuration list for `Disabled-Worlds` may not be functioning as intended.
