### ISSUE TITLE
? Not found. Cant change title

### ISSUE THREAD

**Issue by ryanlach** [joserodpt/RealScoreboard#8]
Hey there i just upgraded realscoreboard to the newest update. Running 1.16.5. I cant seem to change the title of the scoreboard. Even with default config it shows up as “? Not found” was wondering if other had the same issues. I love using realscoreboard so if u could get back to me. Sorry for the minimal info im at work on my phone .
![435C2EB5-67D0-47B9-94D3-1BC217D6AE58](https://user-images.githubusercontent.com/80063243/110009747-6f378380-7ceb-11eb-88ba-4aad961b662b.png)

**Comment by joserodpt** [comment]
Fixed in the new version. Please check it out!

**Comment by joserodpt** [comment]
Let me know if it fixed your problem.

**Comment by ryanlach** [comment]
That fixed it ty :)
