### ISSUE TITLE
BUG that causes Player to disconnect

### ISSUE THREAD

**Issue by Francesco99d** [joserodpt/RealScoreboard#81]
Hi, I'm experiencing from a couple of versions of the plugin, a BUG at the annoying; It is the forced disconnection after a while playing in the Server. 
I am attaching the disconnection message that is provided to me.
![Screenshot 2024-10-03 132035](https://github.com/user-attachments/assets/2cd27027-3279-4f40-9f37-6e97bfc8e940)

P.s. I have noticed that this does not happen when you are OP in the Server and ordinary players experience it more. I have also tried installing different versions of the plugin, from the latest released to some older ones, but nothing. The Server I am using is Purpur 1.20.4: `This server is running Purpur version git-Purpur-2149 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9cd8eb4 on HEAD)` and I use ViaVersion and ViaBackwards to log in with other versions as well. I know it is a problem with this Plugin (or possibly incompatibility of this and something else) because when I remove it, I no longer have this problem

**Comment by joserodpt** [comment]
It might an imcompatibility with ViaVersion or ViaBackwards. Does this happen with the latest paper build? Does it still happen if you remove ViaVersion/ViaBackwards?

**Comment by Francesco99d** [comment]
I honestly haven't tried. Right now I'm updating the version of Purpur (since it was quite old) to see if it works out. Then in case I try removing the other two plugins.

**Comment by Francesco99d** [comment]
Hey there, sorry for the wait in responding to you, but I've been a little busy. Anyway, I did some testing and it would seem that using the SNAPSHOT versions of the “ViaVersion” and “ViaBackwards” plugins, the problem no longer occurs (at least for now). 
I will of course monitor this over the next few days and will be sure to give you more information if anything changes. 
In the meantime, I wish you a good day ;)
