### ISSUE TITLE
Placeholders in Title dont load

### ISSUE THREAD

**Issue by adelando** [joserodpt/RealScoreboard#9]
When using "05-11-2020 Build 1" from Spigot, i used %player_level% in the title in the sidebar but after this update it doesn't display correctly in the title anymore

**Comment by joserodpt** [comment]
Why are you using an old version of the scoreboard?

**Comment by adelando** [comment]
I had been away from my server for about a week and missed all the new updates and when i updated to your latest update i realised that it broke so i had to revert back to a working version.

Running on the latest version
![2021-03-07_16 26 55](https://user-images.githubusercontent.com/11265974/110258050-a9e73780-7fdb-11eb-85ec-251d24fefde8.png)

Running "05-11-2020 Build 1"
![2021-03-07_16 30 20](https://user-images.githubusercontent.com/11265974/110258044-a3f15680-7fdb-11eb-8140-a20819a8d712.png)

**Comment by joserodpt** [comment]
Hi there!
Please test this version. Thanks.

[RealScoreboard.zip](https://github.com/JoseGamerPT/RealScoreboard/files/6098130/RealScoreboard.zip)

**Comment by adelando** [comment]
I tired the updated file, looks like its still not working
The placeholders do work as they are listed below the title.

The "0" under ping is player level and "vault_blah_blah" is next to balance
![2021-03-08_07 46 30](https://user-images.githubusercontent.com/11265974/110259434-84116100-7fe2-11eb-8c6e-52550e727119.png)

**Comment by joserodpt** [comment]
Did you enable the setting in the config?

**Comment by adelando** [comment]
which setting is this? i cannot see any other settings to change for titles

**Comment by joserodpt** [comment]
There is a new setting on config.yml

**Comment by joserodpt** [comment]
just tested this feature, it works.

**Comment by adelando** [comment]
Hi,

yes sorry I re-created my config file and it’s there, toggled it and now it works! 
thanks for your speedy patch!
